/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
const fs = require("fs");
const express = require("express");
const bodyParser = require("body-parser");
const todos = require("./todos.json");

const app = express();
const PORT = 3000;

app.use(bodyParser.json());

app.get("/todos", (req, res) => {
  try {
    res.send(todos).status(200);
  } catch (error) {
    console.log(error);
    res.send(error).status(500);
  }
});

app.get("/todo/:id", (req, res) => {
  const id = req.params.id;
  try {
    const todo = todos.find((todo) => todo.id === id);
    if (!todo) {
      return res.status(404).send("Todo not found");
    }
    res.send(todo).status(200);
  } catch (error) {
    console.log(error);
    res.send(error).status(500);
  }
});

app.post("/todos", (req, res) => {
  const body = req.body;
  try {
    const todo = {
      id: Date.now().toString(),
      title: body.title,
      description: body.description,
      completed: body.completed || false,
    };
    todos.push(todo);
    res.status(201).send(todo);
    fs.writeFileSync("todos.json", JSON.stringify(todos, null, 2));
  } catch (error) {
    console.log(error);
    res.status(500).send(error);
  }
});

app.put("/todos/:id", (req, res) => {
  const id = req.params.id;
  const body = req.body;
  try {
    const todo = todos.find((todo) => todo.id === id);
    if (!todo) {
      res.status(404).send("Todo not found");
    }

    // const updatedTodo = {
    //   ...todo,
    //   title: body.title,
    //   description: body.description,
    //   completed: body.completed,
    // };

    todo.title = body.title ?? todo.title;
    todo.description = body.description ?? todo.description;
    todo.completed = body.completed ?? todo.completed;

    res.status(200).send(todo);
    fs.writeFileSync("todos.json", JSON.stringify(todos, null, 2));
  } catch (error) {
    console.log(error);
    res.status(500).send(error);
  }
});

app.delete("/todos/:id", (req, res) => {
  const id = req.params.id;

  try {
    const todo = todos.find((todo) => todo.id === id);

    if (!todo) {
      return res.status(404).send("Todo not found");
    }

    todos.splice(todos.indexOf(todo), 1);
    res.status(200).send("Todo deleted");
    fs.writeFileSync("todos.json", JSON.stringify(todos, null, 2));
  } catch (error) {
    console.log(error);
    res.status(500).send(error);
  }
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// {
//   "id": "todo_1",
//   "title": "Learn JavaScript Basics",
//   "description": "Revise variables, data types, loops, and functions."
// }

// {
//   "id": "1770148307193",
//   "title": "go gym",
//   "description": "gym jaa bhai",
//   "completed": true
// }

module.exports = app;
